// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msgdatadef_sip.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DICE {

namespace {

const ::google::protobuf::Descriptor* TSipVia_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TSipVia_reflection_ = NULL;
const ::google::protobuf::Descriptor* TSipUri_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TSipUri_reflection_ = NULL;
const ::google::protobuf::Descriptor* TSipVias_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TSipVias_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msgdatadef_5fsip_2eproto() {
  protobuf_AddDesc_msgdatadef_5fsip_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msgdatadef_sip.proto");
  GOOGLE_CHECK(file != NULL);
  TSipVia_descriptor_ = file->message_type(0);
  static const int TSipVia_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVia, uri_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVia, branch_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVia, rport_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVia, received_),
  };
  TSipVia_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TSipVia_descriptor_,
      TSipVia::default_instance_,
      TSipVia_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVia, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVia, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TSipVia));
  TSipUri_descriptor_ = file->message_type(1);
  static const int TSipUri_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipUri, host_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipUri, port_),
  };
  TSipUri_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TSipUri_descriptor_,
      TSipUri::default_instance_,
      TSipUri_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipUri, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipUri, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TSipUri));
  TSipVias_descriptor_ = file->message_type(2);
  static const int TSipVias_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVias, vias_),
  };
  TSipVias_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TSipVias_descriptor_,
      TSipVias::default_instance_,
      TSipVias_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVias, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSipVias, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TSipVias));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msgdatadef_5fsip_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TSipVia_descriptor_, &TSipVia::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TSipUri_descriptor_, &TSipUri::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TSipVias_descriptor_, &TSipVias::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msgdatadef_5fsip_2eproto() {
  delete TSipVia::default_instance_;
  delete TSipVia_reflection_;
  delete TSipUri::default_instance_;
  delete TSipUri_reflection_;
  delete TSipVias::default_instance_;
  delete TSipVias_reflection_;
}

void protobuf_AddDesc_msgdatadef_5fsip_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024msgdatadef_sip.proto\022\004DICE\"V\n\007TSipVia\022"
    "\032\n\003uri\030\001 \002(\0132\r.DICE.TSipUri\022\016\n\006branch\030\002 "
    "\002(\t\022\r\n\005rport\030\003 \001(\t\022\020\n\010received\030\004 \001(\t\"%\n\007"
    "TSipUri\022\014\n\004host\030\001 \002(\t\022\014\n\004port\030\002 \001(\t\"\'\n\010T"
    "SipVias\022\033\n\004vias\030\001 \003(\0132\r.DICE.TSipVia", 196);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msgdatadef_sip.proto", &protobuf_RegisterTypes);
  TSipVia::default_instance_ = new TSipVia();
  TSipUri::default_instance_ = new TSipUri();
  TSipVias::default_instance_ = new TSipVias();
  TSipVia::default_instance_->InitAsDefaultInstance();
  TSipUri::default_instance_->InitAsDefaultInstance();
  TSipVias::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msgdatadef_5fsip_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msgdatadef_5fsip_2eproto {
  StaticDescriptorInitializer_msgdatadef_5fsip_2eproto() {
    protobuf_AddDesc_msgdatadef_5fsip_2eproto();
  }
} static_descriptor_initializer_msgdatadef_5fsip_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int TSipVia::kUriFieldNumber;
const int TSipVia::kBranchFieldNumber;
const int TSipVia::kRportFieldNumber;
const int TSipVia::kReceivedFieldNumber;
#endif  // !_MSC_VER

TSipVia::TSipVia()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TSipVia::InitAsDefaultInstance() {
  uri_ = const_cast< ::DICE::TSipUri*>(&::DICE::TSipUri::default_instance());
}

TSipVia::TSipVia(const TSipVia& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TSipVia::SharedCtor() {
  _cached_size_ = 0;
  uri_ = NULL;
  branch_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  rport_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  received_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TSipVia::~TSipVia() {
  SharedDtor();
}

void TSipVia::SharedDtor() {
  if (branch_ != &::google::protobuf::internal::kEmptyString) {
    delete branch_;
  }
  if (rport_ != &::google::protobuf::internal::kEmptyString) {
    delete rport_;
  }
  if (received_ != &::google::protobuf::internal::kEmptyString) {
    delete received_;
  }
  if (this != default_instance_) {
    delete uri_;
  }
}

void TSipVia::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TSipVia::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TSipVia_descriptor_;
}

const TSipVia& TSipVia::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msgdatadef_5fsip_2eproto();  return *default_instance_;
}

TSipVia* TSipVia::default_instance_ = NULL;

TSipVia* TSipVia::New() const {
  return new TSipVia;
}

void TSipVia::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_uri()) {
      if (uri_ != NULL) uri_->::DICE::TSipUri::Clear();
    }
    if (has_branch()) {
      if (branch_ != &::google::protobuf::internal::kEmptyString) {
        branch_->clear();
      }
    }
    if (has_rport()) {
      if (rport_ != &::google::protobuf::internal::kEmptyString) {
        rport_->clear();
      }
    }
    if (has_received()) {
      if (received_ != &::google::protobuf::internal::kEmptyString) {
        received_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TSipVia::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .DICE.TSipUri uri = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_uri()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_branch;
        break;
      }
      
      // required string branch = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_branch:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_branch()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->branch().data(), this->branch().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_rport;
        break;
      }
      
      // optional string rport = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_rport:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_rport()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->rport().data(), this->rport().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_received;
        break;
      }
      
      // optional string received = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_received:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_received()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->received().data(), this->received().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TSipVia::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .DICE.TSipUri uri = 1;
  if (has_uri()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->uri(), output);
  }
  
  // required string branch = 2;
  if (has_branch()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->branch().data(), this->branch().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->branch(), output);
  }
  
  // optional string rport = 3;
  if (has_rport()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->rport().data(), this->rport().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->rport(), output);
  }
  
  // optional string received = 4;
  if (has_received()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->received().data(), this->received().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->received(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TSipVia::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .DICE.TSipUri uri = 1;
  if (has_uri()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->uri(), target);
  }
  
  // required string branch = 2;
  if (has_branch()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->branch().data(), this->branch().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->branch(), target);
  }
  
  // optional string rport = 3;
  if (has_rport()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->rport().data(), this->rport().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->rport(), target);
  }
  
  // optional string received = 4;
  if (has_received()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->received().data(), this->received().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->received(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TSipVia::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .DICE.TSipUri uri = 1;
    if (has_uri()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->uri());
    }
    
    // required string branch = 2;
    if (has_branch()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->branch());
    }
    
    // optional string rport = 3;
    if (has_rport()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->rport());
    }
    
    // optional string received = 4;
    if (has_received()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->received());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TSipVia::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TSipVia* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TSipVia*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TSipVia::MergeFrom(const TSipVia& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uri()) {
      mutable_uri()->::DICE::TSipUri::MergeFrom(from.uri());
    }
    if (from.has_branch()) {
      set_branch(from.branch());
    }
    if (from.has_rport()) {
      set_rport(from.rport());
    }
    if (from.has_received()) {
      set_received(from.received());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TSipVia::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TSipVia::CopyFrom(const TSipVia& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TSipVia::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  if (has_uri()) {
    if (!this->uri().IsInitialized()) return false;
  }
  return true;
}

void TSipVia::Swap(TSipVia* other) {
  if (other != this) {
    std::swap(uri_, other->uri_);
    std::swap(branch_, other->branch_);
    std::swap(rport_, other->rport_);
    std::swap(received_, other->received_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TSipVia::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TSipVia_descriptor_;
  metadata.reflection = TSipVia_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TSipUri::kHostFieldNumber;
const int TSipUri::kPortFieldNumber;
#endif  // !_MSC_VER

TSipUri::TSipUri()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TSipUri::InitAsDefaultInstance() {
}

TSipUri::TSipUri(const TSipUri& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TSipUri::SharedCtor() {
  _cached_size_ = 0;
  host_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  port_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TSipUri::~TSipUri() {
  SharedDtor();
}

void TSipUri::SharedDtor() {
  if (host_ != &::google::protobuf::internal::kEmptyString) {
    delete host_;
  }
  if (port_ != &::google::protobuf::internal::kEmptyString) {
    delete port_;
  }
  if (this != default_instance_) {
  }
}

void TSipUri::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TSipUri::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TSipUri_descriptor_;
}

const TSipUri& TSipUri::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msgdatadef_5fsip_2eproto();  return *default_instance_;
}

TSipUri* TSipUri::default_instance_ = NULL;

TSipUri* TSipUri::New() const {
  return new TSipUri;
}

void TSipUri::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_host()) {
      if (host_ != &::google::protobuf::internal::kEmptyString) {
        host_->clear();
      }
    }
    if (has_port()) {
      if (port_ != &::google::protobuf::internal::kEmptyString) {
        port_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TSipUri::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string host = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_host()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->host().data(), this->host().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_port;
        break;
      }
      
      // optional string port = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_port:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_port()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->port().data(), this->port().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TSipUri::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string host = 1;
  if (has_host()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->host().data(), this->host().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->host(), output);
  }
  
  // optional string port = 2;
  if (has_port()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->port().data(), this->port().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->port(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TSipUri::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string host = 1;
  if (has_host()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->host().data(), this->host().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->host(), target);
  }
  
  // optional string port = 2;
  if (has_port()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->port().data(), this->port().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->port(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TSipUri::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string host = 1;
    if (has_host()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->host());
    }
    
    // optional string port = 2;
    if (has_port()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->port());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TSipUri::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TSipUri* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TSipUri*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TSipUri::MergeFrom(const TSipUri& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_host()) {
      set_host(from.host());
    }
    if (from.has_port()) {
      set_port(from.port());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TSipUri::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TSipUri::CopyFrom(const TSipUri& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TSipUri::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void TSipUri::Swap(TSipUri* other) {
  if (other != this) {
    std::swap(host_, other->host_);
    std::swap(port_, other->port_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TSipUri::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TSipUri_descriptor_;
  metadata.reflection = TSipUri_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TSipVias::kViasFieldNumber;
#endif  // !_MSC_VER

TSipVias::TSipVias()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TSipVias::InitAsDefaultInstance() {
}

TSipVias::TSipVias(const TSipVias& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TSipVias::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TSipVias::~TSipVias() {
  SharedDtor();
}

void TSipVias::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TSipVias::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TSipVias::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TSipVias_descriptor_;
}

const TSipVias& TSipVias::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msgdatadef_5fsip_2eproto();  return *default_instance_;
}

TSipVias* TSipVias::default_instance_ = NULL;

TSipVias* TSipVias::New() const {
  return new TSipVias;
}

void TSipVias::Clear() {
  vias_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TSipVias::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .DICE.TSipVia vias = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_vias:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_vias()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_vias;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TSipVias::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .DICE.TSipVia vias = 1;
  for (int i = 0; i < this->vias_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->vias(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TSipVias::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .DICE.TSipVia vias = 1;
  for (int i = 0; i < this->vias_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->vias(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TSipVias::ByteSize() const {
  int total_size = 0;
  
  // repeated .DICE.TSipVia vias = 1;
  total_size += 1 * this->vias_size();
  for (int i = 0; i < this->vias_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->vias(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TSipVias::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TSipVias* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TSipVias*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TSipVias::MergeFrom(const TSipVias& from) {
  GOOGLE_CHECK_NE(&from, this);
  vias_.MergeFrom(from.vias_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TSipVias::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TSipVias::CopyFrom(const TSipVias& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TSipVias::IsInitialized() const {
  
  for (int i = 0; i < vias_size(); i++) {
    if (!this->vias(i).IsInitialized()) return false;
  }
  return true;
}

void TSipVias::Swap(TSipVias* other) {
  if (other != this) {
    vias_.Swap(&other->vias_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TSipVias::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TSipVias_descriptor_;
  metadata.reflection = TSipVias_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace DICE

// @@protoc_insertion_point(global_scope)
